services:
  postgres:
    profiles: [ "agent" ]
    # our SQL database
    container_name: spacetraders-postgres
    # based on postgres:15
    image: postgres:16
    ports:
      - "25432:5432"
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spacetraders
      - POSTGRES_PASSWORD=spacetraders-password
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200

  grafana:
    profiles: [ "agent" ]
    image: grafana/grafana-oss
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - postgres
    restart: unless-stopped
    ports:
      - '13000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,frser-sqlite-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./server/grafana-storage:/var/lib/grafana
      - ./server/cfg/grafana/provisioning:/etc/grafana/provisioning

  loki:
    profiles: [ "agent" ]
    image: grafana/loki:3.4.3
    container_name: loki
    depends_on:
      - promtail
    ports:
      - "3100:3100"
    volumes:
      - ./server/loki-data:/loki
      - ./server/cfg/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    profiles: [ "agent" ]
    image: grafana/promtail:3.4.3
    container_name: promtail
    volumes:
      - ./logs:/var/log
      - ./server/cfg/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  prometheus:
    profiles: [ "agent" ]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./server/cfg/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./server/prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
