services:
  postgres:
    profiles: [ "agent" ]
    # our SQL database
    container_name: spacetraders-postgres
    # based on postgres:15
    image: postgres:16
    ports:
      - "25432:5432"
    volumes:
      - ./server/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=spacetraders
      - POSTGRES_PASSWORD=spacetraders-password
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
  grafana:
    profiles: [ "agent" ]
    image: grafana/grafana-oss
    container_name: grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,frser-sqlite-datasource
    volumes:
      - ./server/grafana-storage:/var/lib/grafana
  prometheus:
    profiles: [ "agent" ]
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./server/prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
